### PR TITLE
Returned an isDefault property for calendar

### PR DESCRIPTION
**Pull request by jbuda**

### CODE REVIEW

**Comment by nickrandolph** [comment]
@jbuda do you know whether there's a similar property on Android? We'd like to maintain consistency across the supported platforms (atm iOS and Android).

**Comment by jbuda** [comment]
@nickrandolph Off the top of my head i can't remember. However, I can take a look when i get round to implementing the Calendar into the Android version.

**Comment by nickrandolph** [comment]
@Brett09 I think we can use this field on Android: https://developer.android.com/reference/android/provider/CalendarContract.CalendarColumns.html#IS_PRIMARY

**Comment by Brett09** [comment]
@jbuda thanks for providing iOS support. I'll be merging this with Android support into my branch then create a new PR, hence I'm going to close this.

**Pull request closed without merging**
